//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CacheItem
    {
        public System.Guid CCI_RecordID { get; set; }
        public System.Guid CCI_CAC_RecordID { get; set; }
        public string CCI_Title { get; set; }
        public string CCI_Content { get; set; }
        public System.DateTime CCI_Published { get; set; }
        public string CCI_Labels { get; set; }
    
        public virtual Cache Cache { get; set; }
    }
}
