//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public Child()
        {
            this.Teammates = new HashSet<Teammate>();
        }
    
        public System.Guid CLD_RecordID { get; set; }
        public System.Guid CLD_PRT_RecordID { get; set; }
        public string CLD_FirstName { get; set; }
        public string CLD_LastName { get; set; }
        public System.DateTime CLD_Birthdate { get; set; }
        public bool CLD_Gender { get; set; }
        public string CLD_Notes { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual ICollection<Teammate> Teammates { get; set; }
    }
}
