//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        public Coach()
        {
            this.Phones = new HashSet<Phone>();
        }
    
        public System.Guid CCH_RecordID { get; set; }
        public System.Guid CCH_USR_RecordID { get; set; }
        public System.Guid CCH_PRT_RecordID { get; set; }
        public int CCH_PositionID { get; set; }
        public int CCH_TEM_TeamID { get; set; }
        public Nullable<System.Guid> CCH_PIC_RecordID { get; set; }
        public bool CCH_PRTID { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual Team Team { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
    }
}
