//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public System.Guid CON_RecordID { get; set; }
        public System.Guid CON_PRT_RecordID { get; set; }
        public string CON_Phone { get; set; }
        public string CON_Email { get; set; }
        public Nullable<bool> CON_PRTID { get; set; }
    
        public virtual Parent Parent { get; set; }
    }
}
