//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date
    {
        public System.Guid DTE_RecordID { get; set; }
        public System.DateTime DTE_Day { get; set; }
        public string DTE_Text { get; set; }
        public int DTE_SEA_SeasonID { get; set; }
        public Nullable<int> DTE_Icon { get; set; }
    }
}
