//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPN
    {
        public string IPN_TransactionID { get; set; }
        public Nullable<System.DateTime> IPN_RecieptDate { get; set; }
        public Nullable<decimal> IPN_Amount { get; set; }
        public string IPN_Response { get; set; }
        public string IPN_Email { get; set; }
        public string IPN_Status { get; set; }
        public string IPN_PayerEmail { get; set; }
        public string IPN_PayerLastName { get; set; }
        public string IPN_PMT_RecordID { get; set; }
        public Nullable<bool> IPN_Error { get; set; }
    }
}
