//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public System.Guid ORD_RecordID { get; set; }
        public System.Guid ORD_PRT_RecordID { get; set; }
        public int ORD_SeasonID { get; set; }
        public int ORD_Year { get; set; }
        public int ORD_Volunteer { get; set; }
        public System.DateTime ORD_Date { get; set; }
        public bool ORD_Approved { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
