//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.Children = new HashSet<Child>();
            this.Contacts = new HashSet<Contact>();
            this.Orders = new HashSet<Order>();
            this.Phones = new HashSet<Phone>();
            this.UserLogins = new HashSet<UserLogin>();
        }
    
        public System.Guid PRT_RecordID { get; set; }
        public System.Guid PRT_USR_RecordID { get; set; }
        public string PRT_FatherName { get; set; }
        public string PRT_MotherName { get; set; }
        public string PRT_LastName { get; set; }
        public string PRT_Address { get; set; }
        public string PRT_City { get; set; }
        public string PRT_Zipcode { get; set; }
        public Nullable<bool> PRT_PrimaryEmail { get; set; }
        public Nullable<bool> PRT_PrimaryPhone { get; set; }
    
        public virtual ICollection<Child> Children { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual UserLogin UserLogin { get; set; }
        public virtual ICollection<Phone> Phones { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
    }
}
