//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.Teammates = new HashSet<Teammate>();
        }
    
        public System.Guid PMT_RecordID { get; set; }
        public System.Guid PMT_ORD_RecordID { get; set; }
        public int PMT_Uniforms { get; set; }
        public int PMT_Registrations { get; set; }
        public bool PMT_LateFee { get; set; }
        public int PMT_Total { get; set; }
        public string PMT_IPN_TransactionID { get; set; }
        public System.DateTime PMT_TransactionDate { get; set; }
        public bool PMT_Paid { get; set; }
        public bool PMT_Current { get; set; }
        public Nullable<System.DateTime> PMT_Date { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<Teammate> Teammates { get; set; }
    }
}
