//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.Coaches = new HashSet<Coach>();
            this.Teams = new HashSet<Team>();
            this.Teammates = new HashSet<Teammate>();
        }
    
        public System.Guid PIC_RecordID { get; set; }
        public string PIC_Filename { get; set; }
        public string PIC_Caption { get; set; }
        public System.Guid PIC_ALB_RecordID { get; set; }
        public int PIC_Year { get; set; }
        public int PIC_SeasonID { get; set; }
        public int PIC_TeamID { get; set; }
        public bool PIC_Private { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual ICollection<Coach> Coaches { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
        public virtual ICollection<Teammate> Teammates { get; set; }
    }
}
