//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SKHSSEntities : DbContext
    {
        public SKHSSEntities()
            : base("name=SKHSSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album> Albums { get; set; }
        public DbSet<Cache> Caches { get; set; }
        public DbSet<CacheItem> CacheItems { get; set; }
        public DbSet<Child> Children { get; set; }
        public DbSet<Coach> Coaches { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Feedback> Feedbacks { get; set; }
        public DbSet<IPN> IPNs { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<Phone> Phones { get; set; }
        public DbSet<Picture> Pictures { get; set; }
        public DbSet<SysVar> SysVars { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<Teammate> Teammates { get; set; }
        public DbSet<UserLogin> UserLogins { get; set; }
    
        public virtual ObjectResult<SP_Nearforums_AuthenticateUser_TSQL_Result> SP_Nearforums_AuthenticateUser_TSQL(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Nearforums_AuthenticateUser_TSQL_Result>("SP_Nearforums_AuthenticateUser_TSQL", userNameParameter, passwordParameter);
        }
    }
}
