//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKHSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public UserLogin()
        {
            this.Albums = new HashSet<Album>();
            this.Coaches = new HashSet<Coach>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Parents = new HashSet<Parent>();
        }
    
        public System.Guid USR_RecordID { get; set; }
        public Nullable<System.Guid> USR_PRT_RecordID { get; set; }
        public int USR_UserID { get; set; }
        public int USR_ROL_RoleID { get; set; }
        public string USR_Username { get; set; }
        public string USR_Password { get; set; }
        public string USR_Email { get; set; }
        public string USR_Phone { get; set; }
        public Nullable<System.DateTime> USR_ResetDate { get; set; }
        public bool USR_Activated { get; set; }
        public bool USR_Approved { get; set; }
        public Nullable<bool> USR_Test { get; set; }
        public Nullable<bool> USR_Temp { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Coach> Coaches { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
        public virtual Parent Parent { get; set; }
    }
}
